TRIVIA_DICT = {
    "What is the name of Han Solo’s ship?": "Millennium Falcon",
    "Anakin Skywalker becomes who in Star Wars?": "Darth Vader",
    "The planet Kashyyyk is home to who?": "Chewbacca and the Wookiees",
    "In Revenge of the Sith and Attack of the Clones, what color is Yoda’s lightsaber?": "Green",
    "The X-wing fighter has how many engines?": "Four",
    "Jedi Council consists of how many members?": "12",
    "What were Luke’s aunt and uncle’s jobs on Tatooine?": "Moisture farmers",
    "How many languages is C-3P0 fluent in?": "Over 6 million",
    "Which character is partially named after George Lucas’ son?": "Dexter Jettster",
    "How many Dewbacks were in the original 1977 theatrical cut of the first Star Wars movies?": "Two",
    "What color is Mace Windu’s lightsaber?": "Purple",
    "Who played the part of Mace Windu?": "Samuel L Jackson",
    "Which species stole the plans to the death star?": "Bothans",
    "What kind of trooper is introduced at the beginning of Rogue One?": "Death Troopers",
    "Who kissed Leia first, Han or Luke?": "Luke",
    "What does AT-AT stand for?": "All Terrain Armored Transport",
    "What odds does C-3P0 give Han for successfully navigating the asteroid field?": "3,720 to 1",
    "Who are the masters of the Dark Side that want to rule the galaxy?": "The Sith",
    "Count Dooku is also known as who?": "Darth Tyranus",
    "What is the name of Boba Fett’s ship?": "Slave 1",
    "Who was the original commander of the Death Star?": "Grand Moff Tarkin",
    "What was the name of the planet that the clones were made on?": "Kamino",
    "What is the largest annual podrace in the world?": "The Boonta Eve Classic",
    "When Leia first tells Han Solo that she loves him, what is his reply?": "I know,",
    "What day is Wookiee Life Day?": "November 17th",
    "Peter Mayhew played the part of who in the original Star Wars Trilogy?": "Chewbacca",
    "What language are the words written on Darth Vader’s chest piece in?": "Ancient Hebrew",
    "What is the other name for The Imperial Probe Droid?": "Probot",
    "The four Jedi Masters Kit Fisto, Mace Windu, Agen Kolar, and Saesee Tinn, were killed by who?": "Darth Sidious",
    "Where was Luke Skywalker originally headed to pick up power converters?": "Tosche Station",
    "Which two sectors does The Empire Strikes Back take place in?": "The Sluis Sector and The Anoat Sector",
    "Who’s the only rebel pilot to survive all three movies in the original trilogy?": "Wedge Antilles",
    "What species is Yoda?": "unknown",
    "What is the name of the imperial admiral at the beginning of The Empire Strikes Back?": "Ozzeo",
    "What is the name of the Toydarian who owned Anakin Skywalker?": "Watto",
    "Who was the last one to jump down the Death Star’s garbage chute?": "Han",
    "What race of aquatic sentient beings does Jar-Jar Binks belong to?": "The Gungans",
    "Who killed Han Solo?": "Kylo Ren",
    "Who built C-3P0?": "Anakin Skywalker",
    "What is the name of the organization that builds a blockade around Naboo?": "The Trade Federation",
    "Which actress starred as Queen Amidala’s decoy and hand-maiden Sabè?": "Kiera Knightley",
    "What creature lives in the garbage compactor of the original Death Star?": "Dianoga",
    "What planet does Obi-Wan Kenobi travel to where he discovers an army of clones created for the Republic?": "Kamino",
    "Who is the Sith leader of the Separatist movement?": "Count Dooku",
    "What does the Emperor say is Luke’s weakness?": "His faith in his friends",
    "How many arms does the alien diner owner, Dex Jettster, have?": "Four",
    "What do Han and Luke ride on in the snow on Hoth?": "Tauntaun",
    "Who is Jango Fett’s son?": "Boba Fett",
    "Which arm of Anakin’s does Count Dooku cut off?": "The right",
    "When Luke asked what was in the cave on Dagobah, what was Yoda’s response?": "Only what you take with you",
    "What is Chancellor Palpatine’s malicious Sith alter-ego?": "Darth Sidious",
    "In what detention block” was Princess Leia being held in, in the first Death Star?": "AA-23",
    "What does TIE” stand for in TIE Fighter?": "Twin Ion Engines",
    "Who is the senator that adopts Leia, and what planet is he from?": "Senator Bail Organa",
    "Which Wookiee Jedi Master was renowned for his ability to sense the future?": "Tyvokka",
    "You were right,” were whose last words to Luke?": "Darth Vader",
    "What is the name of the order Darth Sidious gives the clone troopers, which means they will kill all Jedi?": "Order 66",
    "What was the nickname of Snoova, the Wookiee bounty hunter?": "Madclaw",
    "In the Star Wars Holiday Special, which ocean planet was introduced?": "Panna",
    "How many people does Darth Vader kill in The Empire Strikes Back?": "Two",
    "In The Empire Strikes Back, name the two people Darth Vader kills,": "Admiral Ozzel and Captain Needa",
    "What’s the name of the planet where Anakin Skywalker loses the duel against Obi-Wan, which leaves him mangled and burned?": "Mustafar",
    "What do they call the children being trained as Jedi?": "Younglings",
    "What bounty hunter used a bowcaster as his weapon of choice?": "Embo",
    "What can be considered the primary reason for Anakin falling to the dark side?": "He wanted to save Padme",
    "On what planet did Cadbane capture Bolla Ropal?": "Devaron",
    "What is the Rule of 2?": "There can only be two Sith Lords at one time",
    "Who was the composer for every film in the Star Wars Saga?": "John Williams",
    "What are the short junk-collecting aliens on Tatooine called?": "Jawas",
    "What are Luke’s aunt and uncle called?": "Owen and Beru Lars",
    "Where were Luke and Leia born?": "Polis Massa",
    "How big is the exhaust port that is the target for Rebel Alliance Starfighters in A New Hope?": "Two meters",
    "Which planet holds the hidden rebel base?": "Yavin IV",
    "What planet does the Rebel Alliance find refuge on at the beginning of The Empire Strikes Back?": "Hoth",
    "Who is Han’s friend who runs the cloud city of Bespin?": "Lando Calrissian",
    "In what substance is Han Solo frozen for delivery to Jabba the Hutt?": "Carbonite",
    "What race of alien is Admiral Ackbar?": "Mon Calamari",
    "Which year was the film Return of the Jedi released?": "1983",
    "How old is Yoda when he dies?": " 900",
    "What is the name of the Emporer’s Hand who was on Jabba’s sail barge during Han’s rescue?": "Mara Jade",
    "What planet is the second Death Star orbiting in Return of the Jedi?": "Endor",
    "Who infiltrates Jabba’s palace in disguise to save Han Solo?": "Princess Leia",
    "What are the miniature aliens that help the Rebels destroy the shield generator on Endor?": "Ewoks",
    "Who stars as Han Solo in the original Star Wars films?": "Harrison Ford",
    "What makes Han Solo temporarily blind after he is freed from the carbonite?": "Hibernation sickness",
    "What is the name of Lando Calrissian’s co-pilot in Return of the Jedi?": "Nien Nunb",
    "George Lucas’ original last name for Luke was what?": "Starkiller",
    "Han Solo’s trusty blaster is what type of blaster?": "DL-44",
    "How tall is Chewbacca?": "7’6",
    "What planet does Rey live on in The Force Awakens?": "Jakku",
    "Luke Skywalker’s self-imposed exile takes place on what planet?": "Ach-TO",
    "What is Poe Dameron’s droid called?": "BB-8",
    "On which planet does the Resistance have its base?": "D’Qar",
    "How old was Padmè when she became Queen?": "14",
    "Who are Kylo Ren’s father and mother?": "Han Solo and Leia Organa",
    "Who is the cantina owner on Takodana?": "Maz Katana",
    "Who is the supreme leader of the First Order?": "Snoke",
    "What is the name of Luke’s childhood best friend that later served beside him in the rebellion?": "Biggs Darklighter",
    "What is the red substance found on the planet Crait?": "Salt",
}
